-- Reference vocabulary seed for PlayGround Portal.
-- Mirrors the row shapes in src/lib/referenceData.ts.
-- Age-group and category labels come from src/lib/i18n.ts (equipment.cat.* and master.filter.*).
--
-- ⚠️ equipment_catalog rows below are seeded from the EquipmentTypeId union in
-- src/types/playground.ts. label_en / label_pt are PLACEHOLDERS (equal to the type id,
-- matching the app's existing fallback behaviour); replace them with real display names
-- from the design vocabulary. The type -> category mapping is real and fixes the
-- "everything groups under 'development'" bug that occurs when the catalog table is empty.
-- Run against Supabase after apply generate-ddl.sql.

insert into public.age_groups (id, label_en, label_pt, sort_order) values
  ('toddlers',       'Toddlers (0-3)',         'Bebés (0-3)',         1),
  ('preschool',      'Preschool (3-7)',        'Pré-escolar (3-7)',   2),
  ('schoolchildren', 'Schoolchildren (7-12)',  'Escolares (7-12)',    3),
  ('teenagers',      'Teenagers (12+)',        'Adolescentes (12+)',  4),
  ('all',            'All ages',               'Todas as idades',     5)
on conflict (id) do nothing;

insert into public.equipment_categories (id, label_en, label_pt, color, sort_order) values
  ('ride_balance',        'Ride & balance',          'Balanço & equilíbrio',          null, 1),
  ('sport_complex',       'Sport & game',            'Desporto & jogo',               null, 2),
  ('development',         'Development',             'Desenvolvimento',               null, 3),
  ('rest',                'Rest',                    'Descanso',                      null, 4),
  ('exploration',         'Exploration',             'Exploração',                    null, 5),
  ('fitness',             'Fitness',                 'Fitness',                       null, 6),
  ('creativity',          'Creativity',              'Criatividade',                  null, 7),
  ('amenities',           'Amenities',               'Comodidades',                   null, 8),
  ('sensory_play',        'Sensory play',            'Brincadeira sensorial',         null, 9),
  ('adventure_course',    'Adventure course',        'Percurso de aventura',          null, 10),
  ('nature_play',         'Nature play',             'Brincadeira na natureza',       null, 11),
  ('gathering_hub',       'Gathering hub',           'Ponto de encontro',             null, 12),
  ('inclusive_play',      'Inclusive play',          'Brincadeira inclusiva',         null, 13),
  ('toddler_zone',        'Toddler zone',            'Zona de bebés',                 null, 14),
  ('interactive_elements','Interactive elements',    'Elementos interativos',         null, 15),
  ('expanded_amenities',  'Expanded amenities',      'Comodidades alargadas',         null, 16),
  ('tech_play',           'Tech play',               'Brincadeira tecnológica',       null, 17),
  ('water_features',      'Water features',          'Elementos de água',             null, 18),
  ('imaginative_stages',  'Imaginative stages',      'Palcos imaginativos',           null, 19),
  ('sports_zone',         'Sports zone',             'Zona desportiva',               null, 20),
  ('learning_elements',   'Learning elements',       'Elementos de aprendizagem',     null, 21),
  ('maintenance_safety',  'Maintenance & safety',    'Manutenção e segurança',        null, 22),
  ('functional_zones',    'Functional zones',        'Zonas funcionais',              null, 23)
on conflict (id) do nothing;
insert into public.equipment_catalog (type, category_id, label_en, label_pt, default_age_group, sort_order) values
  ('swings_single',          'ride_balance',        'swings_single',          'swings_single',          null, 1),
  ('swings_double',          'ride_balance',        'swings_double',          'swings_double',          null, 2),
  ('swings_triple',          'ride_balance',        'swings_triple',          'swings_triple',          null, 3),
  ('swing_nest',             'ride_balance',        'swing_nest',             'swing_nest',             null, 4),
  ('seesaw',                 'ride_balance',        'seesaw',                 'seesaw',                 null, 5),
  ('carousel',               'ride_balance',        'carousel',               'carousel',               null, 6),
  ('slide',                  'ride_balance',        'slide',                  'slide',                  null, 7),
  ('ladder',                 'sport_complex',       'ladder',                 'ladder',                 null, 8),
  ('wall_bars',              'sport_complex',       'wall_bars',              'wall_bars',              null, 9),
  ('monkey_bars',            'sport_complex',       'monkey_bars',            'monkey_bars',            null, 10),
  ('rope_net',               'sport_complex',       'rope_net',               'rope_net',               null, 11),
  ('pull_up_bar',            'sport_complex',       'pull_up_bar',            'pull_up_bar',            null, 12),
  ('climbing_wall',          'sport_complex',       'climbing_wall',          'climbing_wall',          null, 13),
  ('sandbox',                'development',         'sandbox',                'sandbox',                null, 14),
  ('busy_board',             'development',         'busy_board',             'busy_board',             null, 15),
  ('playhouse',              'development',         'playhouse',              'playhouse',              null, 16),
  ('abacus',                 'development',         'abacus',                 'abacus',                 null, 17),
  ('bench',                  'rest',                'bench',                  'bench',                  null, 18),
  ('trash_bin',              'rest',                'trash_bin',              'trash_bin',              null, 19),
  ('canopy',                 'rest',                'canopy',                 'canopy',                 null, 20),
  ('zip_line',               'exploration',         'zip_line',               'zip_line',               null, 21),
  ('standing_spinner',       'exploration',         'standing_spinner',       'standing_spinner',       null, 22),
  ('spring_rider',           'exploration',         'spring_rider',           'spring_rider',           null, 23),
  ('climbing_dome',          'exploration',         'climbing_dome',          'climbing_dome',          null, 24),
  ('tunnel',                 'exploration',         'tunnel',                 'tunnel',                 null, 25),
  ('gymnastic_rings',        'fitness',             'gymnastic_rings',        'gymnastic_rings',        null, 26),
  ('basketball_hoop',        'fitness',             'basketball_hoop',        'basketball_hoop',        null, 27),
  ('climbing_rope',          'fitness',             'climbing_rope',          'climbing_rope',          null, 28),
  ('balance_beam',           'fitness',             'balance_beam',           'balance_beam',           null, 29),
  ('slackline',              'fitness',             'slackline',              'slackline',              null, 30),
  ('step_stones',            'fitness',             'step_stones',            'step_stones',            null, 31),
  ('water_table',            'creativity',          'water_table',            'water_table',            null, 32),
  ('outdoor_chalkboard',     'creativity',          'outdoor_chalkboard',     'outdoor_chalkboard',     null, 33),
  ('stone_path',             'creativity',          'stone_path',             'stone_path',             null, 34),
  ('telescope',              'creativity',          'telescope',              'telescope',              null, 35),
  ('drinking_fountain',      'amenities',           'drinking_fountain',      'drinking_fountain',      null, 36),
  ('stroller_parking',       'amenities',           'stroller_parking',       'stroller_parking',       null, 37),
  ('music_xylophone',        'sensory_play',        'music_xylophone',        'music_xylophone',        null, 38),
  ('tactile_panel',          'sensory_play',        'tactile_panel',          'tactile_panel',          null, 39),
  ('optical_illusion_panel', 'sensory_play',        'optical_illusion_panel', 'optical_illusion_panel', null, 40),
  ('tic_tac_toe_wall',       'sensory_play',        'tic_tac_toe_wall',       'tic_tac_toe_wall',       null, 41),
  ('in_ground_trampoline',   'adventure_course',    'in_ground_trampoline',   'in_ground_trampoline',   null, 42),
  ('tire_obstacle_course',   'adventure_course',    'tire_obstacle_course',   'tire_obstacle_course',   null, 43),
  ('rope_bridge',            'adventure_course',    'rope_bridge',            'rope_bridge',            null, 44),
  ('jump_rope_station',      'adventure_course',    'jump_rope_station',      'jump_rope_station',      null, 45),
  ('sitting_logs',           'adventure_course',    'sitting_logs',           'sitting_logs',           null, 46),
  ('stone_slide',            'adventure_course',    'stone_slide',            'stone_slide',            null, 47),
  ('natural_climbing_area',  'adventure_course',    'natural_climbing_area',  'natural_climbing_area',  null, 48),
  ('sensory_garden_bed',     'nature_play',         'sensory_garden_bed',     'sensory_garden_bed',     null, 49),
  ('birdhouse_feeder',       'nature_play',         'birdhouse_feeder',       'birdhouse_feeder',       null, 50),
  ('picnic_table_canopy',    'gathering_hub',       'picnic_table_canopy',    'picnic_table_canopy',    null, 51),
  ('table_game_station',     'gathering_hub',       'table_game_station',     'table_game_station',     null, 52),
  ('pet_water_fountain',     'gathering_hub',       'pet_water_fountain',     'pet_water_fountain',     null, 53),
  ('platform_swing',         'inclusive_play',      'platform_swing',         'platform_swing',         null, 54),
  ('accessible_play_table',  'inclusive_play',      'accessible_play_table',  'accessible_play_table',  null, 55),
  ('large_print_panel',      'inclusive_play',      'large_print_panel',      'large_print_panel',      null, 56),
  ('accessible_seating',     'inclusive_play',      'accessible_seating',     'accessible_seating',     null, 57),
  ('mini_slide',             'toddler_zone',        'mini_slide',             'mini_slide',             null, 58),
  ('bee_spring_rider',       'toddler_zone',        'bee_spring_rider',       'bee_spring_rider',       null, 59),
  ('crawling_tunnel',        'toddler_zone',        'crawling_tunnel',        'crawling_tunnel',        null, 60),
  ('soft_play_modules',      'toddler_zone',        'soft_play_modules',      'soft_play_modules',      null, 61),
  ('sand_play_table',        'toddler_zone',        'sand_play_table',        'sand_play_table',        null, 62),
  ('toddler_book_nook',      'toddler_zone',        'toddler_book_nook',      'toddler_book_nook',      null, 63),
  ('sound_effect_board',     'interactive_elements','sound_effect_board',     'sound_effect_board',     null, 64),
  ('musical_pipes',          'interactive_elements','musical_pipes',          'musical_pipes',          null, 65),
  ('u_rack_bike_parking',    'expanded_amenities',  'u_rack_bike_parking',    'u_rack_bike_parking',    null, 66),
  ('modern_park_light',      'expanded_amenities',  'modern_park_light',      'modern_park_light',      null, 67),
  ('bike_repair_station',    'expanded_amenities',  'bike_repair_station',    'bike_repair_station',    null, 68),
  ('smart_gate',             'tech_play',           'smart_gate',             'smart_gate',             null, 69),
  ('digital_game_screen',    'tech_play',           'digital_game_screen',    'digital_game_screen',    null, 70),
  ('interactive_path',       'tech_play',           'interactive_path',       'interactive_path',       null, 71),
  ('ar_info_panel',          'tech_play',           'ar_info_panel',          'ar_info_panel',          null, 72),
  ('kinetic_power_station',  'tech_play',           'kinetic_power_station',  'kinetic_power_station',  null, 73),
  ('cascade_stream',         'water_features',      'cascade_stream',         'cascade_stream',         null, 74),
  ('flower_sprinkler',       'water_features',      'flower_sprinkler',       'flower_sprinkler',       null, 75),
  ('water_wheel',            'water_features',      'water_wheel',            'water_wheel',            null, 76),
  ('market_stall',           'water_features',      'market_stall',           'market_stall',           null, 77),
  ('pedal_pump',             'water_features',      'pedal_pump',             'pedal_pump',             null, 78),
  ('amphitheater_stage',     'imaginative_stages',  'amphitheater_stage',     'amphitheater_stage',     null, 79),
  ('lookout_tower',          'imaginative_stages',  'lookout_tower',          'lookout_tower',          null, 80),
  ('multisport_court',       'sports_zone',         'multisport_court',       'multisport_court',       null, 81),
  ('soccer_pitch',           'sports_zone',         'soccer_pitch',           'soccer_pitch',           null, 82),
  ('calisthenics_frame',     'sports_zone',         'calisthenics_frame',     'calisthenics_frame',     null, 83),
  ('alphabet_panel',         'learning_elements',   'alphabet_panel',         'alphabet_panel',         null, 84),
  ('number_wall',            'learning_elements',   'number_wall',            'number_wall',            null, 85),
  ('compass_floor_design',   'learning_elements',   'compass_floor_design',   'compass_floor_design',   null, 86),
  ('musical_notes_panel',    'learning_elements',   'musical_notes_panel',    'musical_notes_panel',    null, 87),
  ('surveillance_camera',    'maintenance_safety',  'surveillance_camera',    'surveillance_camera',    null, 88),
  ('dog_park_zone',          'functional_zones',    'dog_park_zone',          'dog_park_zone',          null, 89),
  ('shade_structure',        'functional_zones',    'shade_structure',        'shade_structure',        null, 90)
on conflict (type) do nothing;

